name: "/games/tic-tac-toe/bidir_lstm/50k"

model:
  type: "Bidirectional Multihead LSTM"
  lstm_units: 128
  num_lstm_layers: 2
  attention: True

training:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 5

data:
  game: "tic-tac-toe"
  sequence_length: 20
  max_event_length: 50
  path: "/games/tic-tac-toe/50k_single_agent.csv"