name: "/games/tic-tac-toe/bidir_lstm_multihead_50k"

model:
  type: "Bidirectional Multihead LSTM"

training:
  batch_size: 64
  num_epochs: 10

data:
  game: "tic-tac-toe"
  sequence_length: 20
  max_event_length: 50
  path: "/games/tic-tac-toe/50k_single_agent.csv"