name: "games/tic-tac-toe/transformer/transformer_1k"

model:
  type: "Transformer"
  d_model: 64
  num_heads: 8
  ff_dim: 256
  dropout_rate: 0.2

training:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 5

data:
  game: "tic-tac-toe"
  sequence_length: 20
  max_event_length: 50
  path: "/games/tic-tac-toe/1k_single_agent.csv"