name: "cnn_tic_tac_toe_single_agent_1k_model"

model:
  type: "CNN"
  embedding_dim: 128
  num_filters: 100
  filter_sizes: [3, 4, 5]

training:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 5

data:
  game: "tic-tac-toe"
  sequence_length: 20
  max_event_length: 10
  path: "/games/tic-tac-toe/1k_single_agent.csv"