name: "lstm_tic_tac_toe_single_agent_1k_model"

model:
  type: "LSTM"
  hidden_size: 256
  num_layers: 1

training:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 3

data:
  game: "tic-tac-toe"
  sequence_length: 20
  path: "/games/tic-tac-toe/1k_single_agent.csv"