name: "transformer_tic_tac_toe_single_agent_1k_model"

model:
  type: "Transformer"
  embedding_dim: 128
  nhead: 8
  num_encoder_layers: 6

training:
  batch_size: 64
  learning_rate: 0.001
  num_epochs: 5

data:
  game: "tic-tac-toe"
  sequence_length: 20
  max_event_length: 3
  path: "/games/tic-tac-toe/1k_single_agent.csv"